# Site settings
title: "Jonas Schlagenhauf - CV"
description: "Freelance roboticist and software engineer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jonas Schlagenhauf"
resume_title:                   ""

# used for the contact button in _layouts/resume.html
resume_contact_email:           "contact@jschlagenhauf.de"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "79115 Freiburg im Breisgau - Germany - DE"

resume_header_contact_info:     "79115 Freiburg im Breisgau - Germany - DE • contact@jschlagenhauf.de"
display_header_contact_info:    "true"

resume_header_intro: "<p>Hello! I'm a freelance software engineer with a love for robots, drones and everything autonomous.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/schlagenhauf"
  # resume_gitlab_url:            "https://gitlab.com/schlagenhauf"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jonas-schlagenhauf"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://jschlagenhauf.de"
  #resume_medium_url:            "https://medium.com/@jglovier"
  resume_twitter_url:           "http://twitter.com/JonasSchlagenh1"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
